resolver: lts-7.2
compiler: ghcjs-0.2.1.9007002_ghc-8.0.1
compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007002_ghc-8.0.1:
          url: http://ghcjs.tolysz.org/ghc-8.0-2016-10-01-lts-7.2-9007002.tar.gz
          sha1: a41ae415328e2b257d40724d13d1386390c26322

extra-package-dbs: []

flags:
  irc-lib:
    using-ghc: false

packages:
- location: '.'
- location:  '../lib'
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: a63aba90bdea5ae5b3e1506d468613bdfedcdfa3
  extra-dep: true
- location:
    git: git@github.com:Arguggi/reflex-dom.git
    commit: b0ebab4ec85cd4529177b5445c7ef11f1bda2f1b
  extra-dep: true

extra-deps:
- ghcjs-dom-0.2.4.0
- ref-tf-0.4.0.1
- zenc-0.1.1
