resolver: lts-7.2
extra-package-dbs: []

packages:
- location: '.'
- location:  '../lib'
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex.git
    commit: a63aba90bdea5ae5b3e1506d468613bdfedcdfa3
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex-dom.git
    commit: ed3b790f81f8396324fc9a3495de9c911119facc
  extra-dep: true
- location:
    git: https://github.com/jcristovao/newtype-generics
    commit: 001f9db314810f7c5fd2a4c6f536f35cceaa277d
  extra-dep: true

extra-deps:
- ghcjs-dom-0.2.4.0
- ref-tf-0.4.0.1
- zenc-0.1.1
- webkitgtk3-javascriptcore-0.13.2.0
- MemoTrie-0.6.7
